import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import axios from 'axios';
import Link from "next/link";

const Reset = () => {
  const [apiResponse, setApiResponse] = useState('');
  const router = useRouter();

  useEffect(() => {
    const { token } = router.query;
    console.log(apiResponse, "==token")
    if (token) {
      const resetPassword = async () => {
        const data = JSON.stringify({ token });

        const config = {
          method: 'post',
          maxBodyLength: Infinity,
          url: 'https://kyroes.in/st-josephs/api/send-reset-password/',
          headers: {
            'Content-Type': 'application/json',
          },
          data: data,
        };

        try {
          const response = await axios.request(config);
          console.log(response, "==response")
          if(!response.data.error){
            setApiResponse('Password reset successfully, Please check your mail for New Password and Login');
          }
          else{
            setApiResponse('Failed to reset password');
          }
         
        } catch (error) {
          
        }
      };

      resetPassword();
    }
  }, [router.query]);

  const handleLoginRedirect = () => {
    router.push('/');
  };

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/favicon.ico" />
      </Head>
      <main
        className="hold-transition theme-primary bg-img"
        style={{
          backgroundImage: `url("/assets/images/auth-bg/bg-1.jpg")`,
          backgroundSize: 'cover',
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'center',
          width: '100%',
          height: '100vh',
        }}
      >
        <div className="container h-p100">
          <div className="row align-items-center justify-content-md-center h-p100">
            <div className="col-12">
              <div className="row justify-content-center g-0">
                <div className="col-lg-5 col-md-5 col-12">
                  {router.query.token ? (
                    <div className="bg-white rounded10 shadow-lg">
                      <div className="content-top-agile p-20 pb-0">
                        <h2 className="text-primary">Password Reset</h2>
                        <p className="mb-0">{apiResponse}</p>
                      </div>
                      <div className="p-40 text-center">
                        <button className="btn btn-danger mt-10" onClick={handleLoginRedirect}>
                          Login
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div className="bg-white rounded10 shadow-lg">
                      <div className="content-top-agile p-20 pb-0">
                        <h2 className="text-primary">Lets Get Started</h2>
                        <p className="mb-0">Sign in to continue to St Joseph.</p>
                      </div>
                      <div className="p-40">
                        <div className="text-center">
                          <p className="mt-15 mb-0">
                            Redirect to login <Link href="/" className="text-warning ms-5">Sign In</Link>
                          </p>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Reset;
